cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats 
end

cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord

    validates :birth_date, :name, :description, presence: true
    validates :color, presence: true, inclusion: { in: %w(black white orange) }
    validates :sex, presence: true, inclusion: { in: %w(M F) }

end

cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        cat = Cat.new(cat_params)
        if cat.save
            redirect_to cat_url(cat)
        else
            render json: cat.errors.full_messages, status: 422
        end
    end

    private

    def cat_params
        params.require(:cat).permit(:id, :birth_date, :name, :color, :sex, :description)
    end

end

cats/app/helpers/application_helper.rb
module ApplicationHelper
end

cats/app/views/cats/_cats.html.erb
<ul>
    <li>
        <% if action == :show %>
            <a href="<%= cats_url %>">Back to Index</a>
        <% else %>
            <a href="<%= cat_url(cat) %>">Show Page</a>
        <% end %>
    </li>
    <li> <%= cat.id %> </li>
    <li> <%= cat.birth_date %> </li>
    <li> <%= cat.color %> </li>
    <li> <%= cat.name %> </li>
    <li> <%= cat.sex %> </li>
    <li> <%= cat.description %> </li>
</ul>

cats/app/views/cats/_form.html.erb
<% if form_type == :edit %>
     <% action_url = cat_url(cat) %>
     <% button_text = "Edit Cat" %>
 <% else %>
     <% action_url = cats_url %>
     <% button_text = "Create Cat" %>
 <% end %>

 <form action="<%= action_url %>" method="POST">

     <% if form_type == :edit %>
         <input type="hidden" name="_method" value="PATCH">
     <% end %>

     <label>Name
         <input type="text" name="cat[name]" value="<%= cat.name %>">
     </label>

     <label>Birth Date
         <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
     </label>

     <label>Sex
         <input type="text" name="cat[sex]" value="<%= cat.sex %>">
     </label>

     <label>Color
         <input type="text" name="cat[color]" value="<%= cat.color %>">
     </label>

     <label>Description
         <input type="text" name="cat[description]" value="<%= cat.description %>">
     </label>

     <button><%= button_text %></button>

 </form> 

cats/app/views/cats/index.html.erb
<h1>Look at all these kitties!</h1>

<ul>

    <% @cats.each do |cat| %>
        <li>
            <%= render "cats", cat: cat, action: :index %>
        </li>
    <% end %>

</ul>

cats/app/views/cats/new.html.erb
<h1>Make a new cat</h1>

 <%= render "form", cat: @cat, form_type: :new %>

cats/app/views/cats/show.html.erb
<h1>A Cat</h1>


<% render "cats", cat: @cat, action: :show %>


<table>
    <thead>
        <tr>
            <th colspan="6">Cats</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>ID</td>
            <td>NAME</td>
            <td>COLOR</td>
            <td>SEX</td>
            <td>BIRTH DATE</td>
            <td>DESCRIPTION</td>
        </tr>
        <tr>
            <td> <%= @cat.id %> </td>
            <td> <%= @cat.name%> </td>
            <td> <%= @cat.color%> </td>
            <td> <%= @cat.sex%> </td>
            <td> <%= @cat.birth_date%> </td>
            <td> <%= @cat.description%> </td>
        </tr>
    </tbody>
</table>

cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>